### PR TITLE
Resolving Unmanaged<CFErrorRef> warning

### PR DESCRIPTION
**Pull request by JamieWhite**
CFErrorRef is a typealias for CFError that is a struct. Unmanaged is for objects only.

### CODE REVIEW

**Comment by JamieWhite** [comment]
It may not be immediately obvious what needed fixing in this because I've simply moved `Unmanaged<CFErrorRef>` from the function parameter list to inside of the other functions that call it. When I imported the `.framework` file into my project I got the following warning:

https://dl.dropboxusercontent.com/s/36zv2r05xr7xazz/Screenshot%202016-09-05%2014.54.43.png?dl=0

Presumably the compiler doesn't like `Unmanaged<CFErrorRef>` as part of the API

**Comment by danthorpe** [comment]
Hi @JamieWhite - quick question... what version of Swift are you targeting with this?

**Comment by JamieWhite** [comment]
Swift 2.2

**Comment by danthorpe** [comment]
@JamieWhite okay, can you rebase your changes off the `swift/2.2` branch? `development`is currently where Swift 3 work is happening, and `swift/2.2` is for "legacy" _Operations_ v3* stuff. 😁

**Comment by JamieWhite** [comment]
Have just rebased and I think it's screwed up all the build checks

**Comment by danthorpe** [comment]
Yeah, sorry, you might need to try this again... really sorry, but can you also rename the branch to be `swift/2_2/warnings`...

**Pull request closed without merging**
