### PR TITLE
Changes to address GroupProcedure observer bug

### PR DESCRIPTION
**Pull request by danthorpe**
As discussed in #574.

### CODE REVIEW

**Comment by swiftlyfalling** [comment]
@danthorpe: I like how this is evolving.

As a point of clarification: previously, if a GroupProcedure child produced an operation, that operation would be added to the Group's queue, correct? (i.e. as a child of the Group?)

**Comment by danthorpe** [comment]
@swiftlyfalling we did have this special handling previously in _Operations_ (although not originally, I think it was introduced in version 2). However - in the v4 rewrite of `ProcedureQueue` I didn't include this - as there was already some discussions that it wasn't consistent behaviour.

However, that if you have a `GroupProcedure`, and a child in that group (i.e. on the group's queue) calls `produce()`, then this new operation will get added to the receivers queue, which *is* the group's queue. However... the thing is, it will not go through the `add(child: )` API, and so the group will essentially be unaware of it - i.e. it will not wait for it to finish.

This is not a bug, or a defect - that is the intended behaviour of `produce()`, while `add(child:)` is for adding a new child.

**Comment by swiftlyfalling** [comment]
@danthorpe:

With the changes in this PR, a child of a Group that produces an operation will result in the produced operation being waited on by the Group.

(The Group's `procedureQueue(_ queue: ProcedureQueue, willAddOperation operation: Operation)` is called with the produced operation.)

**Comment by danthorpe** [comment]
@swiftlyfalling - I don't think so, in the observer in `ProcedureQueue` there are explicit checks for this [here](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureQueue.swift#L172).

**Comment by danthorpe** [comment]
In terms of a group waiting on _produced_ operations - I guess it'll be best to double check this with some more unit tests - as we don't have that specific test. I'll create another issue to investigate.

**Comment by swiftlyfalling** [comment]
@danthorpe: Please see PR #588. Added a simple test that fails.

**Comment by swiftlyfalling** [comment]
If we want to ensure that:

1. Produced operations do not get waited on by the Group.

2. Produced operations do not trigger multiple calls of observers.

Then we need to ensure that the group does not execute its `willAddOperation` QueueDelegate handler for operations produced by children.

**Pull request merged**
