### PR TITLE
Resolving Unmanaged<CFErrorRef> warning

### PR DESCRIPTION
**Pull request by JamieWhite**
CFErrorRef is a typealias for CFError that is a struct. Unmanaged is for objects only.wq

Updated PR for this discussion https://github.com/ProcedureKit/ProcedureKit/pull/451

### CODE REVIEW

**Comment by JamieWhite** [comment]
How do i find out exactly why this is failing?

**Comment by danthorpe** [comment]
@JamieWhite - don't worry about that single failure - not sure exactly why, but that is still trying to build your `Warnings` branch.

The `swift/2_2/Unmanaged_warnings` is still running.

**Comment by danthorpe** [comment]
Thanks @JamieWhite!

**Comment by JamieWhite** [comment]
No problem. A very minor contribution!

**Pull request merged**
