### PR TITLE
Support Arbitrary mutual exclusion category names

### PR DESCRIPTION
**Pull request by danthorpe**
As discussed in #580.

### CODE REVIEW

**Comment by pronebird** [comment]
So using the following we can set up mutually exclusive operations with arbitrary categories?

```swift
let mutuallyExclusiveWithArbitraryCategory = TrueCondition(name: "Condition 1", mutuallyExclusiveCategory: "Condition 1")
```

**Comment by danthorpe** [comment]
Yes. You can do something like this:

```swift
let foo = Foo()
foo.add(condition: TrueCondition(mutuallyExclusiveCategory: "Red"))
let bar = Bar()
bar.add(condition: TrueCondition(mutuallyExclusiveCategory: "Red"))
let baz = Baz()
baz.add(condition: TrueCondition(mutuallyExclusiveCategory: "Green"))
let bat = Bat()
bat.add(condition: TrueCondition(mutuallyExclusiveCategory: "Green"))
bat.add(condition: TrueCondition(mutuallyExclusiveCategory: "Blue"))
```

**Comment by danthorpe** [comment]
@pronebird feedback on this would be much appreciated - especially when adding multiple exclusive conditions - the test coverage around those scenarios is probably a bit weak, so might want to bear that in mind.

**Comment by pronebird** [comment]
@danthorpe cool. As of now I still maintain a dictionary of category => operations. I'll probably convert it to TrueCondition and let you know if I hit any issues.

**Comment by pronebird** [comment]
Works on a very limited test case.

```swift
    func testSerialExecutionForSimilarRequests() {
        var counter = 0
        
        var expectations = [XCTestExpectation]()
        
        for i in 0..<50 {
            let expect = expectation(description: "Wait for fetch \(i)")
            
            expectations.append(expect)
            
            runOperationWithCategory("MyCategory") { getResult in
                let _ = try! getResult()
                
                DispatchQueue.main.async {
                    print("Finished query \(i)")
                    
                    XCTAssertEqual(counter, i)
                    counter += 1
                    
                    expectations[i].fulfill()
                }
            }
        }
        
        waitForExpectations(timeout: 20)
    }
```

**Comment by ryanjm** [comment]
Using the same setup as before I get this error:

> Type of expression is ambiguous without more context

For this line of code:

```
clearCoreData.add(condition: CoreDataExclusive())
```

My `CoreDataExclusive` is defined as:

```
public enum CoreDataWork { }
public typealias CoreDataExclusive = MutuallyExclusive<CoreDataWork>
```

Any ideas why this error would show up?

**Comment by swiftlyfalling** [comment]
@ryanjm: I am unable to reproduce that error using the latest `development` branch and `Xcode 8.2.1 (8C1002)`. Could you try with `development`?

**Comment by ryanjm** [comment]
Sorry @swiftlyfalling, my fault. I forgot to change my `clearCoreData` from a `BlockOperation` to `BlockProcedure`.

Thank you for taking a look.

**Comment by swiftlyfalling** [comment]
@ryanjm: Ah, yup - that would do it!

**Pull request merged**
