### PR TITLE
Remove push Travis Trigger

### PR DESCRIPTION
**Pull request by danthorpe**
Thanks to comment: https://github.com/ProcedureKit/ProcedureKit/pull/757#issuecomment-314947291

### CODE REVIEW

**Comment by danthorpe** [comment]
@jshier err, not sure about this. Seems like it doesn't build anything adding in your suggestion to `travis.yml`. We still want to run the travis job on PRs. Doesn't seem to be a way to get it to build _only_ PRs.

I don't know, I'm not all that familiar with TravisCI.... any thoughts?

**Comment by jshier** [comment]
Odd. We use this setting on Alamofire just fine. It's also the [accepted answer](https://stackoverflow.com/a/31882307/272952). Perhaps the stages feature is incompatible?

**Comment by jshier** [comment]
I can't see the repo settings, but perhaps make sure the Travis integration is through the actual Travis integration and not a manual webhook?

**Comment by danthorpe** [comment]
Yeah, I think it might be the stages.

- [x] Saw this "accepted answer" - copied settings exactly.
- [x] Setup via GitHub "Integration" not a manual web hook.

Hmm

**Comment by jshier** [comment]
Stages and this setting seem like they should be orthogonal but perhaps not. I read through most of the stages issue for Travis and no one mentioned an issue like this, but I did skim towards the end.

**Pull request closed without merging**
